server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Verket_booking
spring.datasource.username=postgres
spring.datasource.password=123Oppned
spring.datasource.driver-class-name=org.postgresql.Driver

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.from-number=${TWILIO_FROM_NUMBER}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

admin.username=vaerket
admin.password=stats123
